title:          'Minicomp Wiki'
baseurl:        '/wiki'

exclude:        [README.md, LICENSE, Gemfile*, Rakefile, vendor]
permalink:      pretty
search_enabled: true

aux_links:
  'GitHub':
    - 'https://github.com/minicomp/'
  'Wax Demo':
    - 'https://minicomp.github.io/wax/'
  'Ed. Demo':
    - 'https://minicomp.github.io/ed/'

collections:
  sample:
    output: false
    layout: null
    metadata:
      source: sample.csv
    images:
      source: sample_images
